### ISSUE TITLE
Request: Hide Individual Controls from the Controls Bar

### ISSUE THREAD

**Issue by joshua-igor** [gsimon2/hide-player-ui#30]
Many modules add control options for players, crowding the Control Panel on the left side of the screen. It would be a good option to hide individual controls, especially controls from modules. One example is the module "Splatter" that adds a button on the Player's Controls Bar to Hide the Blood due to performance concerns, but all my players have good PCs and will never need to use that option, it would be good to be able to hide that button from them, just like you can hide individual tabs from the Side Bar.

**Comment by gsimon2** [comment]
Its tough to make any thing that is capable to generically apply to UI added by modules since I have to have some knowledge of what they are rendering to be able to hidden it. That being said, I am happy to add support for specific modules upon request. 

When I get  time I can look into Splatter and see what I can do about adding an option to hide those controls.

**Comment by joshua-igor** [comment]
I don't know if it helps with the development, but there is a module that is able to hide any Control Panel button, the module is called [Control Concealer](https://foundryvtt.com/packages/control-concealer) and [Control Controller](https://foundryvtt.com/packages/snugugs-little-helpers).

**Comment by gsimon2** [comment]
This functionality is now added in version 1.7.0. Please let me know if you have any issues or suggestions!
